server:
  port: 8097
  error:
    include-message: always

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/commerce_order_db
    username: root
    password: "Bidyut@07?"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # dev only
    show-sql: true            # dev only
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# ==============================
# EUREKA CONFIG
# ==============================
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8788/eureka
    register-with-eureka: true
    fetch-registry: true

# ==============================
# ACTUATOR + ZIPKIN + TRACING
# ==============================
management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0   # dev ke liye 100%

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# ==============================
# LOGGING (TraceId visible 🔥)
# ==============================
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
